baseURL = 'https://palhares.dev/'
languageCode = 'en-us'
title = 'PalharesDev'

[params]
  description = "Blog pessoal"
  dateFormat = "Jan 2, 2006"

[taxonomies]
  category = "categories"
  author = "authors"